###
GET http://localhost:3000/


###
GET http://localhost:3000/items

###
GET http://localhost:3000/img/tea-black.png

###
Post http://localhost:3000/items
Content-Type: application/json

{
    "title": "Chai Negro",
    "price": 6.99,
    "image": "tea-black.png"
}