###
GET http://localhost:3000/

###
GET http://localhost:3000/items

###
GET http://localhost:3000/items/item
Content-Type: application/json

{
    "itemId":"60e83f9683c7462e7c831da6"
}

###
GET http://localhost:3000/img/tea-black.png

###
Post http://localhost:3000/items
Content-Type: application/json

{
    "title": "Chai Negro",
    "price": 6.99,
    "image": "tea-black.png"
}

###
POST http://localhost:3000/create-payment-intent
Content-Type: application/json

[
    {
        "id": "60e83f9683c7462e7c831da6",
        "qty": 2
    }
]
